# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

"""Frozen-HF visual feature fixture through the QwenAir embedded-input seam.

Set QWENAIR_VISION_ORACLE_BUNDLE to the .pt bundle generated by the frozen
Qwen4-Exp source fixture in Megatron-Bridge. This test exercises the MCore
decoder and PLE path; it does not imply a native vision encoder exists here.
"""

import os

import pytest
import torch

from megatron.core.models.qwenair import QwenAirForCausalLM, QwenAirTextConfig


def _tiny_text_model() -> QwenAirForCausalLM:
    config = QwenAirTextConfig(
        vocab_size=64,
        hidden_size=16,
        num_hidden_layers=2,
        layer_types=["linear_attention", "qwen_sparse_attention"],
        num_attention_heads=2,
        num_key_value_heads=1,
        head_dim=8,
        linear_num_key_heads=2,
        linear_num_value_heads=2,
        linear_key_head_dim=4,
        linear_value_head_dim=4,
        linear_conv_kernel_dim=3,
        hc_count=4,
        hc_lowrank=4,
        num_experts=4,
        num_experts_per_tok=2,
        moe_intermediate_size=8,
        shared_expert_intermediate_size=8,
        indexer_n_heads=2,
        indexer_head_dim=4,
        indexer_budget=4,
        indexer_compress_ratio=2,
        partial_rotary_factor=0.5,
        mrope_section=(1, 1, 0),
        ple_layer_ids=[1],
        ple_embed_dim=16,
        ngram_size=3,
        heads_per_ngram=2,
        ngram_vocab_size_base=7,
        make_ngram_vocab_size_divisible_by=8,
        eos_token_id=3,
        mtp_num_hidden_layers=0,
    )
    return QwenAirForCausalLM(config)


@pytest.mark.parametrize("modality,placeholder", [("image", 31), ("video", 32)])
def test_frozen_hf_visual_features_train_through_text_and_ple(
    modality: str, placeholder: int, monkeypatch: pytest.MonkeyPatch
) -> None:
    """HF feature rows and M-RoPE positions drive MCore CE and gradients."""
    bundle_path = os.environ.get("QWENAIR_VISION_ORACLE_BUNDLE")
    if not bundle_path:
        pytest.skip("Set QWENAIR_VISION_ORACLE_BUNDLE to the frozen HF fixture .pt")
    # MCore's strict FP32 QSA reference requires IEEE matmuls on CUDA.
    monkeypatch.setattr(torch.backends.cuda.matmul, "allow_tf32", False)
    case = torch.load(bundle_path, map_location="cpu", weights_only=True)[modality]
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    torch.manual_seed(1921)
    model = _tiny_text_model().to(device)
    ids = case["input_ids"].to(device)
    positions = case["position_ids"].to(device)
    features = case["features"].to(device).detach().requires_grad_()
    text_embeddings = model.model.embed_tokens(ids)
    placeholder_mask = ids == placeholder
    assert int(placeholder_mask.sum()) == features.shape[0]
    scattered = text_embeddings.masked_scatter(placeholder_mask.unsqueeze(-1), features)
    torch.testing.assert_close(scattered[0, placeholder_mask[0]], features)
    torch.testing.assert_close(
        scattered[0, ~placeholder_mask[0]], text_embeddings[0, ~placeholder_mask[0]]
    )

    labels = ids.clone()
    labels[placeholder_mask] = -100
    output = model(
        None,
        inputs_embeds=scattered,
        ple_input_ids=ids,
        position_ids=positions,
        labels=labels,
    )
    assert output.logits.shape == (*ids.shape, 64)
    assert output.loss is not None and torch.isfinite(output.loss)
    output.loss.backward()
    assert (
        features.grad is not None
        and torch.isfinite(features.grad).all()
        and features.grad.abs().sum() > 0
    )
    ple_weight = model.model.layers[0].ple.ple_embedding.ngram_embedding.weight
    assert (
        ple_weight.grad is not None
        and torch.isfinite(ple_weight.grad).all()
        and ple_weight.grad.abs().sum() > 0
    )
    embedding_weight = model.model.embed_tokens.weight
    assert (
        embedding_weight.grad is not None
        and torch.isfinite(embedding_weight.grad).all()
    )
    assert embedding_weight.grad.abs().sum() > 0

    with pytest.raises(ValueError, match="PLE requires ple_input_ids"):
        model(None, inputs_embeds=scattered.detach(), position_ids=positions)
